config/routes.rb
Rails.application.routes.draw do
  get '/books/new',      :controller => 'books', :action => 'new',    :as => 'new_book'
  post '/books',         :controller => 'books', :action => 'create', :as => 'books'

  get '/books',          :controller => 'books', :action => 'index'
  get '/books/:id',      :controller => 'books', :action => 'show',   :as => 'book'

  get '/books/:id/edit', :controller => 'books', :action => 'edit',   :as => 'edit_book'
  patch '/books/:id',    :controller => 'books', :action => 'update'

  delete '/books/:id',   :controller => 'books', :action => 'destroy'

end

app/models/book.rb
class Book < ActiveRecord::Base
  validates :title, :author, :num_pages, presence: true
  validates :num_pages, numericality: { only_integer: true }
  validate :author_must_be_high_quality

  # validates :author, format: { without: /stephanie meyer/, message: "Can't be Stephanie Meyer"}

  def author_must_be_high_quality
    if author == "stephanie meyer"
      errors.add(:author, "must be high quality")
    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new
    @book.title = params[:title]
    @book.author = params[:author]
    @book.num_pages = params[:num_pages]

    if @book.save
      redirect_to books_url, :notice => "Book created successfully."
    else
      render 'new'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])

    @book.title = params[:title]
    @book.author = params[:author]
    @book.num_pages = params[:num_pages]

    if @book.save
      redirect_to book_url(@book.id), :notice => "Book updated successfully."
    else
      render 'edit'
    end
  end

  def destroy
    @book = Book.find(params[:id])

    @book.destroy

    redirect_to books_url, :notice => "Book deleted."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/edit.html.erb
<!-- Validation failure messages -->

<% if @book.errors.any? %>
  <% @book.errors.full_messages.each do |message| %>
    <div class="alert alert-dismissable alert-danger">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= message %>
    </div>
  <% end %>
<% end %>

<!-- Responsive panel example -->

<div class="row">
  <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Edit Book #<%= @book.id %></h3>
      </div>
      <div class="panel-body">
        <%= form_tag book_url(@book.id), :method => "patch", :class => "form-horizontal" do %>
          <!-- Label and input for title -->
          <div class="form-group">
            <label for="title" class="col-sm-2 control-label">
              Title
            </label>
            <div class="col-sm-10">
              <input type="text" id="title" name="title" placeholder="Title" class="form-control" value="<%= @book.title %>">
            </div>
          </div>

          <!-- Label and input for author -->
          <div class="form-group">
            <label for="author" class="col-sm-2 control-label">
              Author
            </label>
            <div class="col-sm-10">
              <input type="text" id="author" name="author" placeholder="Author" class="form-control" value="<%= @book.author %>">
            </div>
          </div>

          <!-- Label and input for num_pages -->
          <div class="form-group">
            <label for="num_pages" class="col-sm-2 control-label">
              Num pages
            </label>
            <div class="col-sm-10">
              <input type="text" id="num_pages" name="num_pages" placeholder="Num pages" class="form-control" value="<%= @book.num_pages %>">
            </div>
          </div>

          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <input type="submit" value="Update Book" class="btn btn-warning">
              or
              <%= link_to "Cancel", book_url(@book.id) %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>


<!-- End responsive panel example -->

app/views/books/index.html.erb
<div class="page-header">
  <h1>
    Books
    <%= link_to new_book_url, :class => "btn btn-lg btn-success" do %>
      <i class="fa fa-plus"></i>
    <% end  %>
  </h1>
</div>

<!-- Responsive, Isotope-based layout example -->

<div class="row">
  <div class="col-xs-12">
    <input type="text" id="quicksearch" placeholder="Search Books (start typing)" class="form-control">
  </div>
</div>

<hr>

<div class="row isotope-container">
<% @books.each do |book| %>
  <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 isotope-item">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Book #<%= book.id %></h3>
      </div>
      <div class="panel-body">
        <dl>
          <dt>Title</dt>
          <dd><%= book.title %></dd>

          <dt>Author</dt>
          <dd><%= book.author %></dd>

          <dt>Num pages</dt>
          <dd><%= book.num_pages %></dd>

        </dl>
        <div class="btn-group btn-group-justified">
          <%= link_to book_url(book), :class => "btn btn-primary" do %>
            <i class="fa fa-search-plus"></i>
          <% end %>
          <%= link_to edit_book_url(book), :class => "btn btn-warning" do %>
            <i class="fa fa-edit"></i>
          <% end %>
          <%= link_to book_url(book), :method => "delete", :data => { :confirm => "Do you really want to delete this book?" }, :class => "btn btn-danger" do %>
            <i class="fa fa-trash-o"></i>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>
</div>

<!-- JavaScript for Isotope layout and quicksearch -->
<!-- JavaScript for Isotope layout and quicksearch -->
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/3.1.8/imagesloaded.pkgd.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.isotope/2.0.0/isotope.pkgd.min.js"></script>
<script>
  $(function() {
    // quick search regex
    var qsRegex;

    // init Isotope
    var $container = $('.isotope-container');

    $container.imagesLoaded(function() {
      $container.isotope({
        itemSelector: '.isotope-item',
        layoutMode: 'masonry',
        filter: function() {
          return qsRegex ? $(this).text().match( qsRegex ) : true;
        }
      })
    });

    // use value of search field to filter
    var $quicksearch = $('#quicksearch').keyup( debounce( function() {
      qsRegex = new RegExp( $quicksearch.val(), 'gi' );
      $container.isotope();
    }, 200 ) );

  });

  // debounce so filtering doesn't happen every millisecond
  function debounce( fn, threshold ) {
    var timeout;
    return function debounced() {
      if ( timeout ) {
        clearTimeout( timeout );
      }
      function delayed() {
        fn();
        timeout = null;
      }
      timeout = setTimeout( delayed, threshold || 100 );
    }
  }
</script>

<!-- End responsive, Isotope-based layout example -->

app/views/books/new.html.erb
<!-- Validation failure messages -->

<% if @book.errors.any? %>
  <% @book.errors.full_messages.each do |message| %>
    <div class="alert alert-dismissable alert-danger">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= message %>
    </div>
  <% end %>
<% end %>

<!-- Responsive panel example -->

<div class="row">
  <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Add Book</h3>
      </div>
      <div class="panel-body">
        <%= form_tag books_url, :method => "post", :class => "form-horizontal" do %>
          <!-- Label and input for title -->
          <div class="form-group">
            <label for="title" class="col-sm-2 control-label">
              Title
            </label>
            <div class="col-sm-10">
              <input type="text" id="title" name="title" placeholder="Title" class="form-control" value="<%= @book.title %>">
            </div>
          </div>

          <!-- Label and input for author -->
          <div class="form-group">
            <label for="author" class="col-sm-2 control-label">
              Author
            </label>
            <div class="col-sm-10">
              <input type="text" id="author" name="author" placeholder="Author" class="form-control" value="<%= @book.author %>">
            </div>
          </div>

          <!-- Label and input for num_pages -->
          <div class="form-group">
            <label for="num_pages" class="col-sm-2 control-label">
              Num pages
            </label>
            <div class="col-sm-10">
              <input type="text" id="num_pages" name="num_pages" placeholder="Num pages" class="form-control" value="<%= @book.num_pages %>">
            </div>
          </div>

          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <input type="submit" value="Create Book" class="btn btn-success">
              or
              <a href="/books">Cancel</a>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<!-- End responsive panel example -->

app/views/books/show.html.erb
<!-- Responsive panel example-->

<div class="row">
  <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Book #<%= @book.id %></h3>
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-md-12">
            <dl class="dl-horizontal">
              <dt>Title</dt>
              <dd><%= @book.title %></dd>

              <dt>Author</dt>
              <dd><%= @book.author %></dd>

              <dt>Num pages</dt>
              <dd><%= @book.num_pages %></dd>

            </dl>
            <div class="btn-group btn-group-justified">
              <%= link_to books_url, :class => "btn btn-primary" do %>
                <i class="fa fa-chevron-left"></i>
              <% end %>
              <%= link_to edit_book_url(@book.id), :class => "btn btn-warning" do %>
                <i class="fa fa-edit"></i>
              <% end %>
              <%= link_to book_url(@book.id), :method => "delete", :data => { :confirm => "Do you really want to delete this book?" }, :class => "btn btn-danger" do %>
                <i class="fa fa-trash-o"></i>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- End responsive panel example -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>BestBooks</title>


  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">

  <style>
    /* Only necessary if you are using navbar-fixed-top */
    body {
      padding-top: 60px;
    }
  </style>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="/" class="navbar-brand">BestBooks</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/books">Books</a></li>
        <li><a href="#">About</a></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if 1 > 2 %>
          <li><a href="/users/edit">Oscar the Grouch</a></li>
          <li><a href="/users/sign_out" data-method="delete">Sign out</a></li>
        <% else %>
          <li><a href="/users/sign_up">Sign up</a></li>
          <li><a href="/users/sign_in">Sign in</a></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </nav>

  <div class="container">
    <% if notice.present? %>
      <div class="alert alert-dismissable alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= notice %>
      </div>
    <% end %>

    <% if alert.present? %>
      <div class="alert alert-dismissable alert-warning">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= alert %>
      </div>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>